apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/BerriAI/litellm.git
      targetRevision: a10g
      path: deploy/charts/litellm-helm
      helm:
        valueFiles:
          - $values/litellm/values.yaml
    - repoURL: https://github.com/bahn1075/kubeai-cicd.git
      targetRevision: a10g
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: litellm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
