apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bahn1075/kubeai-cicd.git
    targetRevision: main
    path: kubeai
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
