apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeai-models
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bahn1075/kubeai-cicd.git
    targetRevision: main
    path: models
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - AllowEmpty=true
      - Replace=true
      - Force=true
      - PruneLast=true  # Custom Resource를 마지막에 prune (중요!)
      - RespectIgnoreDifferences=true
