apiVersion: v1
kind: Service
metadata:
  name: qwen3-5-9b-ollama
  namespace: kubeai
spec:
  selector:
    model: qwen3-5-9b
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qwen3-5-9b-ollama
  namespace: kubeai
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /qwen3.5
            pathType: Prefix
            backend:
              service:
                name: qwen3-5-9b-ollama
                port:
                  number: 8000
