apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test1
  namespace: kubeai
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /test1
            pathType: Prefix
            backend:
              service:
                name: kubeai
                port:
                  number: 80
