# Kong ingress chart values (chart: kong/ingress 0.22.0)

controller:
  ingressController:
    gatewayDiscovery:
      enabled: true
      generateAdminApiService: true

gateway:
  admin:
    enabled: true
    type: LoadBalancer
    clusterIP: ""
    http:
      enabled: true
    tls:
      enabled: true

  manager:
    enabled: true
    type: LoadBalancer
    http:
      enabled: true
      servicePort: 80
    tls:
      enabled: false

  proxy:
    enabled: true
    type: LoadBalancer

  env:
    role: traditional
    database: "off"
