all:
  enabled: false

catalog:
  exaone3-5-ollama:
    enabled: true
    features: ["TextGeneration"]
    url: "ollama://exaone3.5:latest"
    engine: OLlama
    env:
      OLLAMA_KEEP_ALIVE: "1" # Keep the model loaded in memory
      OLLAMA_MAX_LOADED_MODELS: "1"
      OLLAMA_FLASH_ATTENTION: "true" # Enable Flash Attention
    minReplicas: 0
    scaleDownDelaySeconds: 60
    resourceProfile: nvidia-gpu-a10g:1

  bge-m3-ollama:
    enabled: true
    features: ["TextEmbedding"]
    url: "ollama://bge-m3:latest"
    engine: OLlama
    env:
      OLLAMA_KEEP_ALIVE: "1" # Keep the model loaded in memory
      OLLAMA_MAX_LOADED_MODELS: "1"
      OLLAMA_FLASH_ATTENTION: "true" # Enable Flash Attention
    minReplicas: 0
    scaleDownDelaySeconds: 60
    resourceProfile: nvidia-gpu-a10g:1

  qwen3-5-9b-vllm:
    enabled: true
    features: [TextGeneration]
    url: hf://Qwen/Qwen3.5-9B
    engine: VLLM
    minReplicas: 0
    resourceProfile: nvidia-gpu-a10g:4
    cacheProfile: model-cache-150gb
    args:
      - --max-model-len=4096
      - --max-num-batched-tokens=1024
      - --max-num-seqs=16
      - --tensor-parallel-size=4
      - --gpu-memory-utilization=0.9
      - --language-model-only
      - --enforce-eager

  qwen3-5-27b-claude-4-6-opus-reasoning:
    enabled: true
    features: ["TextGeneration"]
    url: "ollama://moophlo/Qwen3.5-27B-Claude-4.6-Opus-Reasoning-Distilled-GGUF:latest"
    engine: OLlama
    env:
      OLLAMA_KEEP_ALIVE: "1" # Keep the model loaded in memory
      OLLAMA_MAX_LOADED_MODELS: "1"
      OLLAMA_FLASH_ATTENTION: "true" # Enable Flash Attention
    minReplicas: 0
    scaleDownDelaySeconds: 60
    resourceProfile: nvidia-gpu-a10g:1